homeassistant:
  # Name of the location where Home Assistant is running
  name: EmbSys
  # Location required to calculate the time the sun rises and sets
  latitude: 59
  longitude: 26
  # C for Celcius, F for Fahrenheit
  temperature_unit: C
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Tallinn
  #api_password sysemb

# Track the sun
sun:

# View all events in a logbook
logbook:

# Enables support for tracking state changes over time.
history:

# Enables the frontend
frontend:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend
#conversation:

# Show links to resources in log and frontend
#introduction:

group:
  Front door:
    - switch.door_lock

sensor 1:
  platform: command_sensor
  name: CPU
  command: "sh ./scr/cpu_freq.sh"
  unit_of_measurement: "MHz"
  decimal_places: 0

sensor 2:
  platform: command_sensor
  name: door_lock_state
  command: "cat ./data/p2.lock"
  decimal_places: 0

switch door_lock:
  platform: command_switch
  switches:
    Door lock:
      oncmd: "sh ./scr/comm.sh 02 L 1"
      offcmd: "sh ./scr/comm.sh 02 L 0"

automation:
- alias: "Update door lock on"
  trigger:
    platform: numeric_state
    entity_id: sensor.door_lock_state
    above: 1
  action:
    entity_id: switch.door_lock
    service: switch.turn_on

- alias: "Update door lock off"
  trigger:
    platform: numeric_state
    entity_id: sensor.door_lock_state
    below: 1
  action:
    entity_id: switch.door_lock
    service: switch.turn_off

your_project:
