homeassistant:
  # Name of the location where Home Assistant is running
  name: EmbSys
  # Location required to calculate the time the sun rises and sets
  latitude: 59
  longitude: 26
  # C for Celcius, F for Fahrenheit
  temperature_unit: C
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Tallinn
  #api_password sysemb

# Track the sun
sun:

# View all events in a logbook
logbook:

# Enables support for tracking state changes over time.
history:

# Enables the frontend
frontend:

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend
#conversation:

# Show links to resources in log and frontend
#introduction:

hello_world:

group:
  Front Door:
    - switch.door_lock
    - sensor.lock_state
  Outdoor Sensors:
    - sensor.air_temperature
    - sensor.air_humidity
    - sensor.air_pressure
    - sensor.light_intensity
    - sensor.battery_status
  Fish Feeder:
    - sensor.tank_temperature
    - sensor.temperature_status
    - sensor.water_level
    - sensor.light
    - sensor.feed_level
    - sensor.filter_status
  Flower Box:
    - sensor.plant_light
    - sensor.soil_temperature
    - sensor.moisture
    - sensor.humidity
  Water meter:
    - sensor.water_amount
    - sensor.water_temperature
  Indoor lighting:
    - switch.led_1
    - switch.led_2
    - switch.led_3
    - switch.led_4

sensor 41:
  platform: command_sensor_custom
  name: CPU
  command: "sh /home/pi/.homeassistant/scr/cpu_freq.sh"
  unit_of_measurement: "MHz"
  decimal_places: 0

sensor 21:
  platform: command_sensor_custom
  name: Lock state
  command: "getsens p2.lock"
  decimal_places: 0

sensor 31:
  platform: command_sensor_custom
  name: Air temperature
  command: "getsens p3.temp"
  unit_of_measurement: "째C"

sensor 32:
  platform: command_sensor_custom
  name: Air humidity
  command: "getsens p3.humid"
  unit_of_measurement: "%"

sensor 33:
  platform: command_sensor_custom
  name: Air pressure
  command: "getsens p3.pressure"
  unit_of_measurement: "hPa"

sensor 34:
  platform: command_sensor_custom
  name: Light intensity
  command: "getsens p3.light"

sensor 35:
  platform: command_sensor_custom
  name: Battery status
  command: "getsens p3.battery"

sensor 51:
  platform: command_sensor_custom
  name: Light
  command: "getsens p5.light"

sensor 52:
  platform: command_sensor_custom
  name: Water level
  command: "getsens p5.water"

sensor 53:
  platform: command_sensor_custom
  name: Feed level
  command: "getsens p5.feed"

sensor 54:
  platform: command_sensor_custom
  name: Tank temperature
  command: "getsens p5.temp"
  unit_of_measurement: "째C"

sensor 55:
  platform: command_sensor_custom
  name: Temperature status
  command: "getsens p5.temp-state"

sensor 56:
  platform: command_sensor_custom
  name: Filter status
  command: "getsens p5.filter"

sensor 61:
  platform: command_sensor_custom
  name: Plant light
  command: "getsens p6.light"

sensor 62:
  platform: command_sensor_custom
  name: Soil temperature
  command: "getsens p6.temp"
  unit_of_measurement: "째C"

sensor 63:
  platform: command_sensor_custom
  name: Moisture
  command: "getsens p6.moisture"
  unit_of_measurement: "%"

sensor 64:
  platform: command_sensor_custom
  name: Humidity
  command: "getsens p6.humid"
  unit_of_measurement: "%"

sensor 141:
  platform: command_sensor_custom
  name: Water amount
  command: "getsens p14.water"
  unit_of_measurement: "ml"

sensor 142:
  platform: command_sensor_custom
  name: Water temperature
  command: "getsens p14.temp"
  unit_of_measurement: "째C"

light:
  platform: hue

configurator:
  

switch 1:
  platform: command_switch
  switches:
    Door Lock:
      oncmd: "sendcmd 2 L 1"
      offcmd: "sendcmd 2 L 0"

switch 2:
  platform: command_switch
  switches:
    LED 1:
      oncmd: "sendcmd 15 L1 100"
      offcmd: "sendcmd 15 L1 0"
    LED 2:
      oncmd: "sendcmd 15 L2 100"
      offcmd: "sendcmd 15 L2 0"
    LED 3:
      oncmd: "sendcmd 15 L3 100"
      offcmd: "sendcmd 15 L3 0"
    LED 4:
      oncmd: "sendcmd 15 L4 100"
      offcmd: "sendcmd 15 L4 0"

automation:
- alias: "Update door lock on"
  trigger:
    platform: numeric_state
    entity_id: sensor.door_lock_state
    above: 1
  action:
    entity_id: switch.door_lock
    service: switch.turn_on

- alias: "Update door lock off"
  trigger:
    platform: numeric_state
    entity_id: sensor.door_lock_state
    below: 1
  action:
    entity_id: switch.door_lock
    service: switch.turn_off



